apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels: 
    app-name: pod-1
    purpose: pod-affinity
spec:  
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels: 
    app-name: pod-1
    purpose: pod-affinity
spec:  
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: in
            values: pod-1
        topologyKey: "kubernetes.io/zone"
  containers:
  - name: nginx
    image: nginx
